//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class adres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adres()
        {
            this.climber = new HashSet<climber>();
        }
    
        public int cod_adres { get; set; }
        public string street { get; set; }
        public string House { get; set; }
        public string gorod { get; set; }
        public string kvartira { get; set; }
        public string podezd { get; set; }
        public string rayon { get; set; }
        public string oblast { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<climber> climber { get; set; }
    }
}
