//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ascent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ascent()
        {
            this.mountains = new HashSet<mountains>();
            this.pyt = new HashSet<pyt>();
            this.soprov = new HashSet<soprov>();
        }
    
        public int id_ascent { get; set; }
        public System.DateTime datastart { get; set; }
        public System.DateTime dataend { get; set; }
        public int cod_mountains { get; set; }
        public int cod_climber { get; set; }
        public int cod_soprov { get; set; }
        public int koll_uch { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mountains> mountains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pyt> pyt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soprov> soprov { get; set; }
    }
}
