//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adres> adres { get; set; }
        public virtual DbSet<ascent> ascent { get; set; }
        public virtual DbSet<climber> climber { get; set; }
        public virtual DbSet<Dogovor> Dogovor { get; set; }
        public virtual DbSet<history_store> history_store { get; set; }
        public virtual DbSet<mountains> mountains { get; set; }
        public virtual DbSet<neschastnsluchai> neschastnsluchai { get; set; }
        public virtual DbSet<pasport> pasport { get; set; }
        public virtual DbSet<podgotovka> podgotovka { get; set; }
        public virtual DbSet<pyt> pyt { get; set; }
        public virtual DbSet<soprov> soprov { get; set; }
        public virtual DbSet<strana> strana { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
