//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class climber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public climber()
        {
            this.neschastnsluchai = new HashSet<neschastnsluchai>();
        }
    
        public int cod_climber { get; set; }
        public string name_ { get; set; }
        public string familia { get; set; }
        public string otchestvo { get; set; }
        public int cod_adres { get; set; }
        public string telefon { get; set; }
        public int cod_pasporta { get; set; }
        public string email { get; set; }
        public Nullable<int> cod_podgotovki { get; set; }
        public int Cod_dogovora { get; set; }
        public string image { get; set; }
    
        public virtual adres adres { get; set; }
        public virtual Dogovor Dogovor { get; set; }
        public virtual pasport pasport { get; set; }
        public virtual podgotovka podgotovka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<neschastnsluchai> neschastnsluchai { get; set; }
    }
}
