//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class neschastnsluchai
    {
        public int cod_climber { get; set; }
        public int cod_pasporta { get; set; }
        public int cod_soprov { get; set; }
        public string travma { get; set; }
        public string giv_net { get; set; }
        public int kod_sluchay { get; set; }
    
        public virtual climber climber { get; set; }
        public virtual pasport pasport { get; set; }
        public virtual soprov soprov { get; set; }
    }
}
