//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pasport()
        {
            this.climber = new HashSet<climber>();
            this.neschastnsluchai = new HashSet<neschastnsluchai>();
            this.soprov = new HashSet<soprov>();
        }
    
        public int id_pasporta { get; set; }
        public int nomer_pasporta { get; set; }
        public int seria_pasporta { get; set; }
        public int kod_podrazdelenia { get; set; }
        public System.DateTime data_vdachi { get; set; }
        public string kem_vdan { get; set; }
        public string pol { get; set; }
        public string mesto_rogdenia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<climber> climber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<neschastnsluchai> neschastnsluchai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soprov> soprov { get; set; }
    }
}
