//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pyt
    {
        public int cod_mountains { get; set; }
        public Nullable<int> kolostanovok { get; set; }
        public string nameostanoki { get; set; }
        public Nullable<int> rastoyanieostanovkami { get; set; }
        public int cod_soprov { get; set; }
        public int Cod_ascent { get; set; }
        public int cod_pyt { get; set; }
    
        public virtual ascent ascent { get; set; }
        public virtual mountains mountains { get; set; }
        public virtual soprov soprov { get; set; }
    }
}
