//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class soprov
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public soprov()
        {
            this.neschastnsluchai = new HashSet<neschastnsluchai>();
            this.pyt = new HashSet<pyt>();
        }
    
        public int cod_ascent { get; set; }
        public int cod_soprov { get; set; }
        public int cod_pasporta { get; set; }
        public string E_mail { get; set; }
        public string telefon { get; set; }
        public int cod_podgotovki { get; set; }
        public int Cod_dogovora { get; set; }
    
        public virtual ascent ascent { get; set; }
        public virtual Dogovor Dogovor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<neschastnsluchai> neschastnsluchai { get; set; }
        public virtual pasport pasport { get; set; }
        public virtual podgotovka podgotovka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pyt> pyt { get; set; }
    }
}
